### ISSUE TITLE
Support for `.epc` / OOXML files

### ISSUE THREAD

**Issue by sindre-nistad** [Camork/file-expander-plugin#10]
Hi,
Would it be possible to support Microsoft OOXML files in general, and `.epc` files in particular?

These files are regular `.zip` files, with various content, and domain specific XML.

**Comment by Camork** [comment]
@sindre-nistad Hey, could you give me some example file for testing? I am glad to support them if there are regular zip files.

**Comment by sindre-nistad** [comment]
[Emerald_TopC.epc.zip](https://github.com/Camork/file-expander-plugin/files/4799300/Emerald_TopC.epc.zip)

Note that the `.zip` extension was added, so that GitHub would let me upload it.

**Comment by sindre-nistad** [comment]
When I gave it the `.zip` extension in PyCharm, it behaved as expected.

**Comment by Camork** [comment]
Commited in [72d82e0](https://github.com/Camork/file-expander-plugin/commit/72d82e0cbe08c346642cdeaf0fbad67576c4a47c), you can get update from github release page or wait for jetbrains reviewing process.
