### ISSUE TITLE
Folder hidden from view

### ISSUE THREAD

**Issue by fipp** [Camork/file-expander-plugin#11]
Hi! Following a [webinar](https://gradle.com/blog/kotlin-dsl/) on gradle kotlin dsl I noticed that they were able to browse zip files in Intellij IDEA, which I couldn't. I quickly found your plugin but noticed something odd. When browsing the zip file, there is a folder not showing up (`webinar-app/bin/` in my case), which shows up using zipinfo on the terminal.

<img width="403" alt="Screenshot 2020-08-04 at 10 18 42" src="https://user-images.githubusercontent.com/1716906/89270929-4efff300-d63c-11ea-84fb-d4f576b5a04d.png">

If I go into my build script and specify a different name like `bin2`, I see it:

<img width="1078" alt="Screenshot 2020-08-04 at 10 23 14" src="https://user-images.githubusercontent.com/1716906/89271088-866e9f80-d63c-11ea-9f30-67e209e7c2f7.png">

Am I missing something obvious here, or is this a bug?

Using Intellij IDEA 2020.2 Ultimate and File Expander 4.51.

**Comment by Camork** [comment]
@fipp  This bug was fixed in version `1.4`,  or something was missing, could you please share your file?

**Comment by fipp** [comment]
@Camork you mean the plugin file? I have a hard time finding it. I'm on OSX and looking in `/Applications/IntelliJ IDEA.app/Contents/plugins` which seems to be the correct folder, but I'm not seeing anything relevant. I've searched both here and in my user folder, without luck so far. Is there anything special I should search for?

**Comment by fipp** [comment]
@Camork do you mean the plugin file?

**Comment by Camork** [comment]
@fipp I mean the zip file that make you get the bug.

**Comment by fipp** [comment]
@Camork Ah, sure. Here:

[app.zip](https://github.com/Camork/file-expander-plugin/files/5028037/app.zip)

**Comment by Camork** [comment]
@fipp I can't reproduce the bug , can you test the lastst version of [File expander(**v1.5**)](https://plugins.jetbrains.com/plugin/11940-file-expander/versions/stable/93813)?
![image](https://user-images.githubusercontent.com/19710731/89482176-d9c32800-d7cb-11ea-8044-24368e9dc671.png)

**Comment by fipp** [comment]
@Camork It turned out to be my fault. In Editor > File Types I had "bin" included in "Ignore files and folders". Once I removed that I saw the folder. Nothing wrong with your plugin so.

Sorry for the noise.
