### ISSUE TITLE
Allow configuring supported file extensions

### ISSUE THREAD

**Issue by antimirov** [Camork/file-expander-plugin#13]
**Describe the bug**
(This is not a bug, it's a feature request, I just could not find a way to submit that)
I'm using PyCharm where I'm building .whl (wheel) packages. At the moment .whl is not supported by your plugin even though it's just a .zip file:

```
$ file my_pkg-0.0.7-py3-none-any.whl
my_pkg-0.0.7-py3-none-any.whl: Zip archive data, at least v2.0 to extract
```

It would be great if this plugin supports detecting ZIP files by using of a library similar to `libmagic` or at least allowed editing a list with custom extensions, like in this case it would be `[".whl"]`

Thank you!

### Environment & Stack Trace
- Plugin version:  1.6
- IDE version: 
- Operating System and version: 
- Stack Trace:

**Comment by Camork** [comment]
I would take a try with dynamic detect zip based files, thanks for giving suggestion.

**Comment by wrnunzio** [comment]
This is exactly what i need!
The only difference is that i got ".resource" files that should\can be treated as standard zip files.
I am really looking forward to this new feature.
Thanks for your work Camork.

**Comment by Camork** [comment]
By adding the wanted file extension to the file type which is named "Archive (ARCHIVE(extend))". You can add a file extension named whatever you want to support a zip-based file. 
![image](https://user-images.githubusercontent.com/19710731/95049980-5ff0e180-071d-11eb-84d3-9af899216729.png)

**Comment by antimirov** [comment]
It works, thank you very much!
