### ISSUE TITLE
[Feature] Add support for NAR archives (and potentially JAR-related files regardless of their actual extension)

### ISSUE THREAD

**Issue by lmserrano** [Camork/file-expander-plugin#14]
**Is your feature request related to a problem? Please describe.**
There are other Java archives which are similar with JARs but have a different extension, such as NiFi Archive (NAR) files, but also others. It would be nice if the plugin would provide the expansion symbol on those too, and would allow the user to click and attempt to expand, like it does for JAR archives. This would improve compatibility with many more file formats which are JAR-related.

**Describe the solution you'd like**
It would be nice to be able to work with NAR files as if they were JAR files too.

**Additional context**
Nothing to add.

**Comment by Camork** [comment]
Does this solution meet your needs? see comment here(https://github.com/Camork/file-expander-plugin/issues/13#issuecomment-703447419)

**Comment by lmserrano** [comment]
@Camork it works! Thank you and sorry for not noticing you already support this feature by allowing plugin configuration! Great job!
