### ISSUE TITLE
Copying files fails on Windows

### ISSUE THREAD

**Issue by josephjthomas** [Camork/file-expander-plugin#16]
**Describe the bug**
If I have the plugin enabled, select a file and press CTRL+C and press CTRL+V in a folder to copy it to the desired location nothing appears, the clipboard is empty. The same happens if you use CTRL+X to cut and CTRL+V to paste.
The same behavior can be obtained if you right click a .jar and select "Copy" and "Paste" in a different folder.
Disabling the plugin makes everything work again.

### Environment & Stack Trace
- Plugin version: 1.7
- IDE version: 2021.1.3
- Operating System and version: Windows 10 Version 21H1 (Build 19043.1083)
- Stack Trace: None

**Comment by Camork** [comment]
I will look into it. But it won't be quickly.

**Comment by TanqiZhou** [comment]
我的也会，快2023了

**Comment by motionrus** [comment]
on my mac same problem 🥲

**Comment by Camork** [comment]
Fix in version 2.0.
