### ISSUE TITLE
Not opening .aar files

### ISSUE THREAD

**Issue by nschwermann** [Camork/file-expander-plugin#17]
Will not let me expand .aar files must rename them to .zip or .jar

### Environment & Stack Trace
- Plugin version:   1.7
- IDE version: 2021.2.1
- Operating System and version:  OSX
- Stack Trace: N/A

**Comment by Camork** [comment]
You can reference to this [issue](https://github.com/Camork/file-expander-plugin/issues/13)

**Comment by nschwermann** [comment]
Yep that did it thanks!
