### ISSUE TITLE
[Feature] Add support for VCS status colors

### ISSUE THREAD

**Issue by jasonex7** [Camork/file-expander-plugin#18]
**Is your feature request related to a problem? Please describe.**
I have trouble trying to figure out the status of a jar file in the VCS, if is modified, added or not yet added to the VCS.

**Describe the solution you'd like**
It would help if the color of the filename in Project Explorer reflects the status in VCS as like it shows without using the plugin

**Additional context**
This is with the plugin disabled:
![image](https://user-images.githubusercontent.com/16229253/175328600-eb674450-372d-4c9b-9b2d-b8bc5f8fdaea.png)

This is with the plugin activated:
![image](https://user-images.githubusercontent.com/16229253/175328778-a9061773-2d50-4dca-9d4b-fc935615d0c0.png)

**Comment by Camork** [comment]
Fix in version 2.0
