### ISSUE TITLE
Update build tool dependencies

### ISSUE THREAD

**Issue by YannCebron** [Camork/file-expander-plugin#19]
1) https://github.com/Camork/file-expander-plugin/blob/master/build.gradle#L3
update to 1.8.1 and always update to latest release to support building against latest IDE releases

2) Gradle 7.5.1, also keep current https://github.com/Camork/file-expander-plugin/blob/master/gradle/wrapper/gradle-wrapper.properties#L3

**Comment by Camork** [comment]
Resolved
