### ISSUE TITLE
Duplicate "File Expander2" plugin on JetBrains Marketplace

### ISSUE THREAD

**Issue by justint** [Camork/file-expander-plugin#21]
Hey @Camork, I came across this other plugin on the JetBrains Marketplace that looks like an exact replica of yours:

https://plugins.jetbrains.com/plugin/19799-file-expander2

Nearly identical description, same links to your repo, but a different author/vendor. It raised a red flag to me as someone trying to impersonate your plugin.

**Comment by Camork** [comment]
Thanks for letting me know that, It was not created by me ,  Maybe someone downloaded the code and republished. After all the source code is opened for public.

**Comment by Camork** [comment]
I have report it to jetbrains people. and it should have hidden from the marketplace.
