### ISSUE TITLE
Selecting file in explorer does nothing

### ISSUE THREAD

**Issue by wilsjame** [Camork/file-expander-plugin#23]
**Describe the bug**
Selecting .7z and .gz file types in solution explorer does nothing. 

### Environment & Stack Trace
- Plugin version: 2.0
- IDE version: JetBrains Rider 2022.2.3
- Operating System and version: macOS Ventura Version 13.0

**Comment by Camork** [comment]
Hey @wilsjame , I notice the **solution explorer**, could you please give me a screenshot? I have no experience on Rider.

> **Describe the bug** Selecting .7z and .gz file types in solution explorer does nothing.
> 
> ### Environment & Stack Trace
> * Plugin version: 2.0
> * IDE version: JetBrains Rider 2022.2.3
> * Operating System and version: macOS Ventura Version 13.0

**Comment by wilsjame** [comment]
Thank you for the response! Here is a screenshot of a selected .gz file in my **solution explorer**. No drop down context appears on the selected file and nothing appears to happen in my  main window. Please let me know if I'm doing anything wrong or if I can provide more information. Thank you again!

![Untitled](https://user-images.githubusercontent.com/23319994/200396430-7688d687-1baf-4ffc-b51b-5d7da3315670.png)

![image](https://user-images.githubusercontent.com/23319994/200395597-09e31bed-cf09-49b8-83a2-78674b668c97.png)

**Comment by Camork** [comment]
After some researching, I thought it was unable to implemented in Rider , or some products which are not based on intellij family, The solution view is diffrent than the project view which the file-expander-plugin applyed to. And the part of  Rider's sources code is not visible to the public.

**Comment by germgerm** [comment]
So this plugin does not work with Rider ?
The "_Compatible with all IntelliJ-based IDEs_" bit should be revised
