### ISSUE TITLE
Broken in IntelliJ IDEA 2022.3 (Community Edition)

### ISSUE THREAD

**Issue by nickjmv** [Camork/file-expander-plugin#24]
**Describe the bug**
I don't have the option anymore for expanding .tgz files after upgrading my IntelliJ to 2022.3. I already tried reinstalling the plugin without success.

IntelliJ IDEA 2022.3 (Community Edition)
Build #IC-223.7571.182, built on November 29, 2022
Runtime version: 17.0.5+1-b653.14 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

### Environment & Stack Trace
- Plugin version: 2.0
- IDE version: IDEA 2022.3
- Operating System and version: MacOS Ventura 13.0.1
- Stack Trace: /

**Comment by Camork** [comment]
An update is pending for marketplace's approval , thanks for reporting the bug.
