### ISSUE TITLE
[Feature] support .ear (enterprise java archive) 

### ISSUE THREAD

**Issue by ghynx** [Camork/file-expander-plugin#30]
**Is your feature request related to a problem? Please describe.**
.ear files (at least some file using zip or jar compression)  are not expandables 
 
**Describe the solution you'd like**
Provide the same behaviour as .jar or .zip files 

**Additional context**

**Comment by Camork** [comment]
Can you check if this plugin work for the jar files?  The ear files should be work currently.

**Comment by ghynx** [comment]
Hello , sorry for the late response ... 
yes it work with .jar files .
I had a little look at the code ... i suspect it could be related to CoreUtils.groovy where ARCHIVES_EXTENSIONS doesn't include 'ear' as a valid compressed file . 
Can't provide a patch / PR now , but it should be easy to check .
Thx.

**Comment by Camork** [comment]
But the ear was included in the [code](https://github.com/Camork/file-expander-plugin/blob/d73b3cfb6b0fcceefe719d7c922b009b34ce0f20/src/main/groovy/com/github/camork/extensions/ArchiveTreeProvider.groovy#L40),  It would be weird if it not working. or you can check [this issue](https://github.com/Camork/file-expander-plugin/issues/13) to configure any extensions which should be recognized.

**Comment by ghynx** [comment]
My Bad .... 
Found that the .ear i worked on was generated using zip not using jar . 
Using standard compression method ( it's a gradle project so i'll use ear instead of zip task ), the plugin works as expected 

Sorry for disturbing
