### ISSUE TITLE
IDEA version 2023.2 doesn't work

### ISSUE THREAD

**Issue by CleanCodeWillKeepYouAlive** [Camork/file-expander-plugin#32]
**Describe the bug**
Apparently plugin doesn't work for latest version of IDEA.
Enable/Disable doesn't help as well as Caches invalidation
### Environment & Stack Trace
- Plugin version: 2.1  
- IDE version:  IDEA 2023.2 
- Operating System and version:  OSX Ventura 13.4.1

**Comment by Camork** [comment]
Can you check again ?  Is there any error log popup or something I can know.  I have tested with the community version without any problems.
