### ISSUE TITLE
[Bug] If the .whl file is inside a tar.gz file, it will not expand

### ISSUE THREAD

**Issue by sla-te** [Camork/file-expander-plugin#33]
**Is your feature request related to a problem? Please describe.**
![image](https://github.com/Camork/file-expander-plugin/assets/22568014/73f51229-c2da-498b-9f1e-565fa9c14dea)

**Describe the solution you'd like**
It should expand like any other archive

**Additional context**
I found https://github.com/Camork/file-expander-plugin/issues/13 and it does work if the whl file is not archived but not if it is.

**Comment by Camork** [comment]
I will take a look. this case may be not handled.

**Comment by Camork** [comment]
Resolved in v2.2,  you may receive update from marketplace.
