### ISSUE TITLE
Not detecting .war files

### ISSUE THREAD

**Issue by cwensel** [Camork/file-expander-plugin#37]
**Describe the bug**
.war files are not being expanded. If renamed to .jar, the file is expanded in the ide.

### Environment & Stack Trace
- Plugin version:  2.3
- IDE version: IntelliJ IDEA 2023.2.5 (Ultimate Edition)
- Operating System and version: 14.1.2 (23B92)
- Stack Trace: n/a

**Comment by Camork** [comment]
Can you check the `File Types` configuration in settings about `Archive (ARCHIVE)` or Archive `(EXTEND ARCHIVE)`, it should be enabled by default.
<img width="709" alt="image" src="https://github.com/Camork/file-expander-plugin/assets/19710731/1b7abf4a-0625-4495-8194-09da7ceb8d21">

**Comment by cwensel** [comment]
that was it! thanks!

threw me off because the icon associated with it was for an archive file. so I assumed it was associated.
