### ISSUE TITLE
Support for tgz extension

### ISSUE THREAD

**Issue by gkfirst8** [Camork/file-expander-plugin#5]
Great support. Works nicely with tar & tar.gz. Would you be willing to also support tgz extension? It would need to do exactly the same as tar.gz does.

**Comment by Camork** [comment]
Hey @gkfirst8 ,nice suggestion. I will take a look to implement it.

**Comment by Camork** [comment]
Hey @gkfirst8 , the commit was merged https://github.com/Camork/file-expander-plugin/pull/6 , It will take two days to push to Jetbrain repos, you can download the latest build from [release page](https://github.com/Camork/file-expander-plugin/releases/tag/1.1).

**Comment by gkfirst8** [comment]
This works, thanks!
